{{- if and .Values.secrets.github.create .Values.secrets.github.data }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.github.name }}
  namespace: {{ .Values.namespace.name | default .Release.Namespace }}
  labels:
    {{- include "llm.labels" . | nindent 4 }}
type: Opaque
stringData:
  .env: |
{{- range $k, $v := .Values.secrets.github.data }}
    {{ $k }}={{ $v }}
{{- end }}
{{- end }}
